---
 - name: Copy the content to HAProxy
   copy:
     content: "{{ content_proxy }}"
     dest: "{{ file_name }}"
   when:
     - "'proxy' in group_names"
     - "'webserver' in group_names"
    



